- package-lock.json
- package.json
- src/api/api.ts
- src/api/axiosInstance.ts
- src/app/layout.tsx
- src/components/auth/signup/SignupForm.tsx
- src/providers/TanstackProvider.tsx
회원가입 기능 임시로 작동X
어떤 변경사항이 있나요?
axios
tanstack/react-query
tanstack/react-query-devtools
> ✨Feat/signup: 회원가입 기능(임시)

- src/api/api.ts
- src/api/axiosInstance.ts
- src/components/auth/login/LoginForm.tsx
- src/components/auth/signup/SignupForm.tsx
> ✨Feat: 로그인 기능(임시)

- src/api/api.ts
- src/api/axiosInstance.ts
- src/components/auth/signup/SignupForm.tsx
> ✨Feat:  로그인 회원가입 기능 추가

- src/app/(auth)/signup/page.tsx
- src/assets/styles/global.css
- src/components/auth/signup/SignupForm.tsx
> 💄Style: 회원가입 웹 퍼블리싱

- src/app/dashboard/page.tsx
- src/app/diary/create/page.tsx
- src/app/diary/page.tsx
- src/app/guide/page.tsx
- src/app/layout.tsx
- src/components/common/MobileTitle.tsx
- src/components/common/Sidebar.tsx
- src/components/diary/DiaryDetailClient.tsx
- src/components/profile/ProfileClient.tsx
생활기록, 대쉬보드, 프로필, 가이드 스크롤 오류 수정 / 모바일 헤더 수정
어떤 변경사항이 있나요?
> 💄 Style: 일부 페이지 스크롤 오류 수정

- src/app/admin/[type]/page.tsx
- src/app/admin/page.tsx
- src/components/admin/AdminTable.tsx
- src/components/admin/AdminTableContainer.tsx
- src/components/admin/ReportDetail.tsx
- src/components/admin/ReportModal.tsx
- src/components/admin/StatusGraph.tsx
관리자 페이지 퍼블리싱 - 신고 상세내역, 모달, selectbox 추가
어떤 변경사항이 있나요?
> 💄 Style: 신고 상세내역, 모달, selectbox 추가

- src/components/admin/ReportModal.tsx
> 💄 Style: 관리자 신고 모달 수정

- src/components/common/Header.tsx
- src/components/home/LandingFeature.tsx
- src/components/notification/NotificationModal.tsx
- 마이페이지, 알림 아이콘 위치 수정
- 랜딩 페이지 feature 영역 텍스트 여백 수정
- 알림 모달창 퍼블리싱
어떤 변경사항이 있나요?
> 💄 Style: 알림 모달창 퍼블리싱

- src/app/(main)/post/[category]/page.tsx
- src/components/common/SearchBar.tsx
- src/components/common/SelectBox.tsx
> 💄Style: select box width 수정

- src/app/(main)/admin/[type]/page.tsx
- src/components/admin/AdminTableContainer.tsx
- src/components/admin/StatusGraph.tsx
관리자 페이지 글자크기, 간격 수정
어떤 변경사항이 있나요?
> 💄 Style: 관리자 페이지 글자크기, 간격 수정

- src/components/notification/NotificationModal.tsx
- 알림 목록 hover effect 버그 수정
- 타이틀 커서 수정
어떤 변경사항이 있나요?
> 💄 Style: 알림 모달 UI 수정

- src/components/common/Header.tsx
- src/components/common/Sidebar.tsx
- src/stores/sidebarStore.ts
모바일 sidebar toggle 기능 추가
어떤 변경사항이 있나요?
https://github.com/user-attachments/assets/b1df59c1-c153-4e64-897d-81d55d2a0560
> ✨Feat/sidebar: 모바일 sidebar toggle 기능 추가

- src/assets/data/pet.ts
- src/components/common/Button.tsx
- src/components/profile/dog/DogProfileEdit.tsx
- src/components/profile/dog/DogProfileEditMobile.tsx
- src/components/profile/dog/DogProfileList.tsx
- src/components/profile/dog/VaccineInfo.tsx
- src/components/profile/dog/VaccineInput.tsx
- src/components/profile/dog/VaccineItem.tsx
- src/components/profile/dog/VaccineModal.tsx
- src/lib/hooks/usePetForm.ts
- src/lib/hooks/useVaccineForm.ts
> 🐛 Fix: 백신 오류 수정 / 일부 예외 처리 / tanstack query 적용

- src/api/pet.ts
- src/api/user.ts
- src/components/profile/ProfileClient.tsx
- src/components/profile/dog/DogProfileCard.tsx
- src/components/profile/dog/DogProfileEdit.tsx
- src/components/profile/dog/DogProfileEditMobile.tsx
- src/components/profile/dog/DogProfileList.tsx
- src/components/profile/dog/VaccineModal.tsx
- src/components/profile/user/NicknameField.tsx
- src/components/profile/user/PasswordField.tsx
- src/components/profile/user/UserProfile.tsx
- src/components/profile/user/UserProfileEdit.tsx
- src/components/profile/user/UserProfileEditMobile.tsx
- src/lib/hooks/usePassword.ts
- src/lib/hooks/usePetForm.ts
- src/lib/hooks/useProfiles.ts
- src/types/pet.d.ts
- src/types/user.d.ts
> ✨ Feat: 유저 정보 수정/탈퇴, 일부 오류 수정

- src/app/not-found.tsx
404 버튼에 메인페이지 링크 연결
어떤 변경사항이 있나요?
> ✨ Feat: 404 메인페이지 링크 연결

- src/components/auth/login/LoginForm.tsx
- src/components/auth/signup/EmailInputSection.tsx
- src/components/auth/signup/NicknameInputSection.tsx
- src/components/auth/terms/TermsAgreement.tsx
> 💄Style: 회원가입 피드백 반영

- src/components/admin/ReportModal.tsx
> 🐛 Fix: null 데이터 관련 수정

- src/app/(main)/admin/page.tsx
- src/components/admin/AdminTable.tsx
- src/components/admin/BarChart.tsx
- src/components/admin/GroupedBarChart.tsx
- src/components/admin/ReportModal.tsx
> 💄 Style: 관리자페이지 다크모드 적용

- src/api/schedule.ts
- src/components/schedule/CustomCalendar.tsx
- src/components/schedule/MobileSchedule.tsx
- src/components/schedule/TodoItem.tsx
관리자 페이지 - api 경로 수정, nopet 컴포넌트 중복 해결
어떤 변경사항이 있나요?
> 🔧 Chore: 일정 api 경로 수정

- src/components/admin/AdminTableContainer.tsx
> 🔧 Chore: console.log 삭제

- src/api/dashboard.ts
- src/components/dashboard/DashboardClient.tsx
- src/components/dashboard/FeedCard.tsx
- src/components/dashboard/ProfileCard.tsx
- src/components/dashboard/WalkCard.tsx
- src/components/dashboard/graph/BarGraph.tsx
- src/components/dashboard/graph/DonutGraph.tsx
- src/components/dashboard/graph/LineGraphCard.tsx
- src/components/schedule/NoPets.tsx
- src/types/dashboard.d.ts
💄 Style: 대시보드 예외처리/반응형 수정
어떤 변경사항이 있나요?
> 💄 Style: 대시보드 예외처리/반응형 수정

- src/components/common/SelectBox.tsx
Style: 모바일 신고 모달 selectbox 너비 수정
어떤 변경사항이 있나요?
> 💄Style: 모바일 신고 모달 selectbox 너비 수정

- src/app/(main)/post/[category]/loading.tsx
> 💄Style: 포스트 리스트 로딩 페이지 수정

- src/components/dashboard/FeedCard.tsx
- src/components/dashboard/graph/DonutGraph.tsx
> 🐛 Fix: 소수점 오류 수정

- src/components/common/PopupMenu.tsx
- src/components/common/SearchBar.tsx
- src/components/common/Settings.tsx
- src/components/common/WriterInfo.tsx
- src/components/post/PostCard.tsx
- src/components/post/PostList.tsx
> 💄Style: 디자인 피드백 반영

- src/components/common/Header.tsx
- src/components/profile/ProfileClient.tsx
- src/components/profile/user/NicknameField.tsx
- src/components/profile/user/UserProfile.tsx
- src/components/profile/user/UserProfileEdit.tsx
- src/components/profile/user/UserProfileEditMobile.tsx
- src/lib/hooks/profile/useProfiles.ts
> 🐛 Fix: 닉네임 중복확인 로직 변경

- src/components/common/WriterInfo.tsx
> 🐛Fix: 신고 모달 오류 수정

- src/components/profile/user/UserProfileEdit.tsx
- src/components/profile/user/UserProfileEditMobile.tsx
🐛 Fix: 패스워드 alert Toast로 변경
어떤 변경사항이 있나요?
> 🐛 Fix: 패스워드 alert Toast로 변경

- src/components/post/PostCard.tsx
게시글 2번 이동되는 문제 수정
어떤 변경사항이 있나요?
> 🐛Fix: 게시글 2번 이동되는 문제 수정

- src/app/global-error.tsx
- src/components/dashboard/ProfileCard.tsx
> 💄 Style: 오류 페이지 구현

- src/components/profile/dog/DogProfileList.tsx
> 🐛 Fix: Swiper nextEl 오류 수정

- src/components/auth/login/LoginForm.tsx
- src/components/auth/signup/PasswordInputSection.tsx
> 🐛Fix: 소셜로그인도 알림 세팅 추가

- src/components/auth/login/LoginForm.tsx
- src/components/auth/signup/PasswordInputSection.tsx
Reverts prgrms-web-devcourse-final-project/WEB4_5_404TNF_FE#157
> Revert "🐛Fix: 소셜로그인도 알림 세팅 추가"
